// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFOY5sHaKEk09x2Vp55hjuh7z13nvEiYE',
    appId: '1:221525420935:web:39cd3a45f7ee59a3098122',
    messagingSenderId: '221525420935',
    projectId: 'webserve-a49c3',
    authDomain: 'webserve-a49c3.firebaseapp.com',
    storageBucket: 'webserve-a49c3.firebasestorage.app',
    measurementId: 'G-K5H09GJDBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSy27Q0tygei2mmzTF0eCj5LDHMdp5QEk',
    appId: '1:221525420935:android:5c0d17952b38c159098122',
    messagingSenderId: '221525420935',
    projectId: 'webserve-a49c3',
    storageBucket: 'webserve-a49c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ-TwJZpCZva-RjpoQClgi3PBGtcb6cio',
    appId: '1:221525420935:ios:fb250e42c68045cd098122',
    messagingSenderId: '221525420935',
    projectId: 'webserve-a49c3',
    storageBucket: 'webserve-a49c3.firebasestorage.app',
    iosBundleId: 'com.example.testdndk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ-TwJZpCZva-RjpoQClgi3PBGtcb6cio',
    appId: '1:221525420935:ios:fb250e42c68045cd098122',
    messagingSenderId: '221525420935',
    projectId: 'webserve-a49c3',
    storageBucket: 'webserve-a49c3.firebasestorage.app',
    iosBundleId: 'com.example.testdndk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFOY5sHaKEk09x2Vp55hjuh7z13nvEiYE',
    appId: '1:221525420935:web:06fb603281b3d137098122',
    messagingSenderId: '221525420935',
    projectId: 'webserve-a49c3',
    authDomain: 'webserve-a49c3.firebaseapp.com',
    storageBucket: 'webserve-a49c3.firebasestorage.app',
    measurementId: 'G-Q072HDWL1G',
  );
}
